export const WHITEBOARD_SCENARIOS = [
  {
    id: "chat",
    label: "Quick Chat",
    prompt: "What's the capital of France?",
    response: "The capital of France is Paris. It's the largest city in France and serves as the country's political, economic, and cultural center.",
    systemSize: 3,
    promptSize: 8,
    responseSize: 12,
    contextLimit: 100,
  },
  {
    id: "code",
    label: "Code Review",
    prompt: "Review this React component for performance issues:\n\nfunction UserList({ users }) {\n  const [filter, setFilter] = useState('');\n  const filtered = users.filter(u =>\n    u.name.toLowerCase().includes(filter)\n  );\n  return (\n    <div>\n      <input onChange={e => setFilter(e.target.value)} />\n      {filtered.map(u => <UserCard key={u.id} user={u} />)}\n    </div>\n  );\n}",
    response: "I see a few performance issues:\n\n1. filtered recalculates on every render — wrap it in useMemo.\n2. The input onChange creates a new function each render — use useCallback.\n3. UserCard likely needs React.memo to prevent unnecessary re-renders.\n\nHere's the optimized version:\n\nfunction UserList({ users }) {\n  const [filter, setFilter] = useState('');\n  const handleChange = useCallback(e => setFilter(e.target.value), []);\n  const filtered = useMemo(() =>\n    users.filter(u => u.name.toLowerCase().includes(filter)),\n    [users, filter]\n  );\n  return (\n    <div>\n      <input onChange={handleChange} />\n      {filtered.map(u => <UserCard key={u.id} user={u} />)}\n    </div>\n  );\n}",
    systemSize: 5,
    promptSize: 30,
    responseSize: 45,
    contextLimit: 100,
  },
  {
    id: "long",
    label: "Long Document",
    prompt: "Summarize this 50-page research paper on climate change mitigation strategies, carbon capture technology, renewable energy adoption rates across different economies, policy frameworks for emissions reduction, and the economic impacts of transitioning away from fossil fuels...\n\n[... 49 more pages of dense academic text covering methodology, findings across 30 countries, statistical analyses, future projections through 2050, and policy recommendations ...]",
    response: "Key findings from the paper:\n\n1. Carbon capture is viable but expensive — $50-120/ton\n2. Solar adoption outpacing projections by 3x\n3. Policy matters more than technology alone",
    systemSize: 3,
    promptSize: 85,
    responseSize: 10,
    contextLimit: 100,
  },
  {
    id: "overflow",
    label: "Overflow",
    prompt: "Here's my entire codebase — all 200 files, including every test, config file, and documentation page. I need you to understand all of it and then refactor the authentication system while maintaining backwards compatibility with every existing API consumer...\n\n[... massive codebase dump: hundreds of files, thousands of lines, entire git history, CI/CD configs, deployment scripts, database schemas ...]",
    response: "",
    systemSize: 5,
    promptSize: 120,
    responseSize: 25,
    contextLimit: 100,
  },
];
